export const popularProductsData = [
    {
        id: '001',
        productTitle: 'Black Full body suit',
        productType: 'full body resistance',
        productPrice: '5000 INR',
        src: '/Images/productImage3.png',
        alt: 'Image1',
    },
    {
        id: '002',
        productTitle: 'Full body rubber suit',
        productType: 'full body resistance',
        productPrice: '8000 INR',
        src: '/Images/productImage2.png',
        alt: 'Image2',
    },
    {
        id: '003',
        productTitle: 'Natural Industrial Aprons',
        productType: 'full body resistance',
        productPrice: '3000 INR',
        src: '/Images/productImage1.png',
        alt: 'Image3',
    },
    {
        id: '004',
        productTitle: 'Chemical Resistance suit',
        productType: 'full body resistance',
        productPrice: '6000 INR',
        src: '/Images/productImage4.png',
        alt: 'Image4',
    },
    {
        id: '005',
        productTitle: 'Black Full body suit',
        productType: 'full body resistance',
        productPrice: '5000 INR',
        src: '/Images/productImage3.png',
        alt: 'Image1',
    },
    {
        id: '006',
        productTitle: 'Full body rubber suit',
        productType: 'full body resistance',
        productPrice: '8000 INR',
        src: '/Images/productImage2.png',
        alt: 'Image2',
    },
    {
        id: '007',
        productTitle: 'Natural Industrial Aprons',
        productType: 'full body resistance',
        productPrice: '3000 INR',
        src: '/Images/productImage1.png',
        alt: 'Image3',
    },
    {
        id: '008',
        productTitle: 'Chemical Resistance suit',
        productType: 'full body resistance',
        productPrice: '6000 INR',
        src: '/Images/productImage4.png',
        alt: 'Image4',
    },
]
