export { default as Carrot } from './carrot.svg'
export { default as RightArrow } from './RightArrow.svg'
export { default as ChatIcon } from './chatIcon.svg'
export { default as Star } from './star.svg'
export { default as Rs } from './Rs.svg'
