export const aboutUsLables = {
    topImgHead : "About us",
    topImgText : "Unveiling the Threads of Our Story",

    overviewHead : "Overview",
    overviewSubTitle : "Uniform on web the top manufacturers and suppliers of customize wholesale corporate uniforms, was established in the year --------- at New Delhi, Delhi/NCR-India.",
    overviewText : "If you want to know about modern design, comfortable corporate and industrial staff working uniforms price near me or looking to buy custom men and women corporate uniform In India you are at the right place. We have 20+ years of experience & expertise in manufacturing unique and extraordinary uniforms for different streams. We make extraordinary designs by blending the right concepts, color, methods and fabrics which is later metamorphosed to extraordinary uniforms. We have a range of products waiting to be used by our valuable customers. We are specialized corporate and industry custom design uniform manufacturers in India",
    
    sideImgText1 : "We “uniform on web” are a sole proprietorship based firm, engaged as the foremost manufacturer, wholesaler and retailer of corporate clothing and workwear uniforms.",
    sideImgText2 : "Our range of logo uniform work Wear for Mens and women includes:-hospital staff uniforms, hospitality uniforms, beauty salons uniforms, receptionist uniforms, industrial uniforms, restaurant & bar uniforms, cafe uniforms, staff uniforms, air hostess uniforms chefs uniforms, engineers maintenance uniforms, factory workers uniforms, security guard uniform, construction uniforms, spa uniform, nursing uniforms, sports uniform, retail store uniform, gas station staff uniforms, gym staff uniforms, patient uniforms, departmental store uniforms ,horticulture safety uniforms, peon uniforms, photographers uniforms, drivers uniforms, plumbing & electrical workers uniforms, hostel staff uniforms. And many more.",
    sideImgText3 : "All our corporate uniform unisex uniforms are developed following the current fashion trends and as per the industry guidelines. Owing to excellent fitting, color fastness, intricate designs and comfortability, our products are widely acclaimed by the clients across the globe -Canada, Mexico and the United States, Austria, Belgium, Bulgaria, Croatia, Republic of Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, Netherlands, Poland, Portugal, Romania, Slovakia, Slovenia, Spain and Sweden. Saudi Arabia, Kuwait, Yemen, Oman, Bahrain, Hong Kong, Japan, Macau, Mongolia and South Korea.",
    
    descriptionText1 : "Being a customer-oriented organization, all our efforts are directed towards winning the optimum level of satisfaction for our clients. Our entire range is developed by a team of designers and craftsmen, keeping in mind the set parameters of quality. We are also known as trusted manufacturers and suppliers of custom design professional workwear corporate apparel in India for all the products as per our clients' demand and choice. Moreover, customers can avail these uniforms at reasonable prices and hence, avoid their budgetary constraints.",
    descriptionText2Light : "Our Business markets include ",
    descriptionText2Dark : "Gurugram, Manesar, Delhi, Mumbai, Bangalore, Hyderabad, Ahmedabad, Chennai, Kolkata, Surat, Ghaziabad, Ludhiana, Agra, Nashik, Faridabad, Meerut, Rajkot, Kalyan-Dombivali, Vasai-Virar, Varanasi, Srinagar, Pune, Jaipur, Lucknow, Kanpur, Nagpur, Indore, Thane, Bhopal, Visakhapatnam, Pimpri-Chinchwad, Patna and Vadodara.",
    descriptionText3 : "Feel free to contact us for any type of latest design corporate uniform for office staff requirements. Our team is committed towards giving the best service with best result hence our qualified team ensures timely delivery of excellent high quality custom logo corporate uniform to our customers.",
    descriptionBtn : "contact now",

    factsheetHead : "Factsheet",
    businessHead : "Nature of Business -",
    business : "Manufacturer, Wholesaler, Trader, Retailer, Supplier, Distributor",
    ceoHead : "Company CEO -",
    ceoName : "Mr. Joshi",
    locationHead : "Company location -",
    locationAdd : "New Delhi- 110051, Delhi, India",
    employeeHead : "Total Number of Employees -",
    employeeNo : "Unto 10 People",
    yearHead : "Year of Establishment -",
    yearOfEstablishment : "2000",
    statusHead : "Legal Status of Firm Individual -",
    status : "Proprietor",
    turnoverHead : "Annual Turnover -",
    turnover : "Rs. 1 - 3 Crore",

    uspHead : "Company USP",
    uspTeaxt1 : "Primary Competitive Advantage",
    uspTeaxt2 : "Experienced R & D Department",
    uspTeaxt3 : "Good Financial Position & TQM",
    uspTeaxt4 : "Large Product Line",
    uspTeaxt5 : "Large Production Capacity",
    uspTeaxt6 : "Provide Customized Solutions",
    uspTeaxt7 : "Quality Measures / Testing Facilities Yes",

    profileHead : "Statutory Profile",
    profileTeaxt1 : "Banker",
    profileTeaxt2 : "ABC-------------------",
    profileTeaxt3 : "ABC-------------",
    profileTeaxt4 : "GST No.------- ABCDEFGH",
    profileTeaxt5 : "HSN Code",

    hsnHead : "HSN Description",
    hsnNo1 : "6113",
    hsnText1 : "Garments, made up of knited or crocheted fabrics of heading 5903, 5906 or 5907",
    hsnNo2 : "6217",
    hsnText2 : "Other made up clothing accessories; parts of garments or of clothing accessories, other than those of heading 6212",

    teamHead : "Our Team",
    teamText1 : "We are assisted by a team of diligent professionals at every stage of our designing and stitching process. All these experts are hired after going through stringent recruitment procedures, which includes practical exams and face to face interviews. To complete the tasks successfully, our professionals work in close coordination among each other. Moreover, these experts also maintain friendly relationships with the clients so as to know their exact needs and fulfill the same in a streamlined manner.",
    teamText2 : "Further, to keep our experts abreast of the changing trends that emerge in the fashion industry, we arrange regular training sessions, seminars, exhibitions and workshops.",
    
    membersHead : "Our team consists of the following members",
    member1 : "Designers",
    member2 : "Skilled tailoring professionals",
    member3 : "Client relation executives",
    member4 : "Warehousing managers",
    member5 : "Packaging experts",
    member6 : "Sales and marketing personnel",

    paymentHead : "Packaging/Payment and Shipment Details",
    paymentMode1 : "Payment Mode",
    paymentMode2 : "Cash",
    paymentMode3 : "Credit Card",
    paymentMode4 : "Bank Transfer",
    paymentMode5 : "DD",
    paymentMode6 : "Cheque",
    paymentMode7 : "Online",
    shipmentMode : "Shipment Mode By Road",

    whyUsHead : "Why Us?",
    whyUsText : "We are widely recognized in this sector due to our premium quality and trendy range of garments which we provide in several colors, patterns and designs. Due to the following unique reasons, we are able to carve a niche in this field:",
    whyUs1 : "State-of-the-art infrastructural base",
    whyUs2 : "Affordable price structure",
    whyUs3 : "Wide range of garments",
    whyUs4 : "Customized options",
    whyUs5: "Quality-proven range",
    whyUs6 : "Prompt delivery",
    whyUs7 : "Positive records",
    whyUs8 : "Adroit team of professionals",
    whyUs9 : "Well equipped warehouse",
    whyUs10 : "Timely delivery",
    whyUs11 : "Wide distribution network",


}