export const dropdownLabels = {
    industrialClothingHead: 'Industrial Clothing',
    securityGuardUniformHead: 'Security Guard Uniform',
    commercialUniformHead: 'Commercial  Uniforms',
    corporateUniformHead: 'Corporate Uniform',
    hospitalUniformHead: 'Hospital Uniforms',
    hotelUniformHead: 'Hotel Uniforms',
    schoolUniformHead: 'School Uniforms',
}

export const industrialClothing = [
    { id: 1, name: 'Safety Suits' },
    { id: 2, name: 'Work Clothes' },
    { id: 3, name: 'Industrial Aprons' },
    { id: 4, name: 'Bee Veil' },
    { id: 5, name: 'Chemical Resistant Clothing' },
    { id: 6, name: 'Rubber Suit' },
    { id: 7, name: 'Insulated Clothing' },
    { id: 8, name: 'Fire Proximity Suits' },
    { id: 9, name: 'Reflective Clothing' },
    { id: 10, name: 'Industrial Coverall' },
    { id: 11, name: 'Work Shirts' },
    { id: 12, name: 'ESD Garments' },
    { id: 13, name: 'Safety T Shirt' },
    { id: 14, name: 'Safety Shirt' },
    { id: 15, name: 'Working Trouser' },
    { id: 16, name: 'High Visibility Clothing' },
    { id: 17, name: 'Industrial Trousers' },
    { id: 18, name: 'Sand Blasting Suit' },
    { id: 19, name: 'Immersion Suit' },
]

export const securityGuardUniform = [
    { id: 1, name: 'Men Security Uniform' },
    { id: 2, name: 'Security Guard Shoes' },
    { id: 3, name: 'Security Guard Belt' },
    { id: 4, name: 'Security Guard Caps' },
    { id: 5, name: 'Security Guard Shirt' },
    { id: 6, name: 'Security Jacket' },
]

export const commercialUniform = [
    { id: 1, name: 'Worker Uniform' },
    { id: 2, name: 'Scout Uniforms' },
    { id: 3, name: 'Staff Uniform' },
    { id: 4, name: 'Corporate Uniform' },
    { id: 5, name: 'Promotional Uniform' },
    { id: 6, name: 'Driver Uniform' },
    { id: 7, name: 'Driver Uniform' },
    { id: 8, name: 'Uniform Accessories' },
    { id: 9, name: 'Petrol Pump Uniform' },
    { id: 10, name: 'Doctor Coat' },
    { id: 11, name: 'Advocate Gown' },
    { id: 12, name: 'Housekeeping Uniform' },
    { id: 13, name: 'Uniform Pants' },
    { id: 14, name: 'College Uniform' },
    { id: 15, name: 'Uniform Belts' },
    { id: 16, name: 'SPA Uniform' },
    { id: 17, name: 'Air Hostess Uniform' },
    { id: 18, name: 'Uniform Shirt' },
    { id: 19, name: 'Technician Uniform' },
    { id: 20, name: 'Uniform Cap' },
    { id: 21, name: 'Sales Uniform' },
    { id: 22, name: 'Drama Dress' },
    { id: 23, name: 'Photographer Jackets' },
    { id: 24, name: 'Pilot Uniform' },
    { id: 25, name: 'Institutional Uniform' },
    { id: 26, name: 'Ladies Housekeeping Uniform' },
    { id: 27, name: 'Uniform Necktie' },
]

export const corporateUniform = [
    { id: 1, name: 'Uniform Saree' },
    { id: 2, name: 'Logo T Shirt' },
    { id: 3, name: 'Men Corporate T Shirt' },
    { id: 4, name: 'Men Corporate Uniform' },
    { id: 5, name: 'Office Wear' },
    { id: 6, name: 'Ladies Corporate Uniform' },
    { id: 7, name: 'Men Corporate Shirt' },
    { id: 8, name: 'Corporate Shirt' },
    { id: 9, name: 'Men Dress Socks' },
    { id: 10, name: 'Executive Shirt' },
]

export const hospitalUniform = [
    { id: 1, name: 'Doctor Coat' },
    { id: 2, name: 'Lab Apron' },
    { id: 3, name: 'Disposable Lab Coat' },
    { id: 4, name: 'School Lab Coat' },
    { id: 5, name: 'Nonwoven Lab Coat' },
    { id: 6, name: 'Scrub Suits' },
    { id: 7, name: 'Nurse Uniform' },
    { id: 8, name: 'Medical Apron' },
    { id: 9, name: 'Medical Scrub' },
    { id: 10, name: 'Pharmaceutical Uniform' },
    { id: 11, name: 'Nurse Coat' },
    { id: 12, name: 'Ward Boy Uniform' },
    { id: 13, name: 'Medical Scrub Set' },
    { id: 14, name: 'Dentist Apron' },
    { id: 15, name: 'Scrub Tops' },
    { id: 16, name: 'Nurse Cap' },
    { id: 17, name: 'Cotton Scrubs' },
    { id: 18, name: 'Nurse Tops' },
    { id: 19, name: 'Scrub Pant' },
]

export const hotelUniform = [
    { id: 1, name: 'Housekeeping Uniform' },
    { id: 2, name: 'Chef Coats' },
    { id: 3, name: 'Waiter Uniform' },
    { id: 4, name: 'Catering Uniform' },
    { id: 5, name: 'Restaurant Uniform' },
    { id: 6, name: 'Chef Uniform' },
    { id: 7, name: 'Bell Boy Uniform' },
    { id: 8, name: 'Chef Caps' },
    { id: 9, name: 'Oven Mitt' },
    { id: 10, name: 'Chef Hat' },
    { id: 11, name: 'Chef Pants' },
    { id: 12, name: 'Chef Scarf' },
    { id: 13, name: 'Chef Shirt' },
    { id: 14, name: 'Chef Skull Cap' },
]

export const schoolUniform = [
    { id: 1, name: 'Kids School Uniforms' },
    { id: 2, name: 'School T Shirts' },
    { id: 3, name: 'School Belt' },
    { id: 4, name: 'School Tie' },
    { id: 5, name: 'School Uniform Shirt' },
    { id: 6, name: 'Boys School Uniform' },
    { id: 7, name: 'School Blazer' },
    { id: 8, name: 'School Sweater' },
    { id: 9, name: 'Girls School Uniform' },
    { id: 10, name: 'School Sports Uniform' },
    { id: 11, name: 'School Tracksuit' },
    { id: 12, name: 'School Trousers' },
]
